import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';

// SHARED
import { Permission } from '@shared/entities/role/permission.entity';
import {
  PERMISSION_AFFILIATE,
  PERMISSION_BRANCH,
  PERMISSION_CAMPAIGN,
  PERMISSION_COMPANY,
  PERMISSION_CUSTOMER,
  PERMISSION_CUSTOMER_CARE,
  PERMISSION_DEPARTMENT,
  PERMISSION_KEY,
  PERMISSION_MARKETING,
  PERMISSION_NAME,
  PERMISSION_PG,
  PERMISSION_POSITION,
  PERMISSION_REGION,
  PERMISSION_SALE_ADMIN,
  PERMISSION_SERVICE,
  PERMISSION_SERVICE_PACK,
  PERMISSION_STOCK_BRANCH,
  PERMISSION_STOCK_COMPANY,
  PERMISSION_TECHNICAL_STAFF,
  PERMISSION_USER,
} from '@shared/constants/permission.constants';

function generateData(permissionName: string, permissionKey: string) {
  return {
    permissionName: permissionName,
    permissionKey: permissionKey,
    createdAt: '2022-02-22 22:22:22.222222 +00:00',
    updatedAt: '2022-02-22 22:22:22.222222 +00:00',
  };
}

const dataPosition = [
  // Position
  generateData(PERMISSION_NAME[PERMISSION_POSITION.LIST_POSITION], PERMISSION_POSITION.LIST_POSITION),
  generateData(
    PERMISSION_NAME[PERMISSION_POSITION.CREATE_UPDATE_REMOVE_POSITION],
    PERMISSION_POSITION.CREATE_UPDATE_REMOVE_POSITION,
  ),
  generateData(PERMISSION_NAME[PERMISSION_POSITION.LIST_ALL_POSITION], PERMISSION_POSITION.LIST_ALL_POSITION),
];

const dataUser = [
  // User
  generateData(PERMISSION_NAME[PERMISSION_USER.LIST_USER], PERMISSION_USER.LIST_USER),
  generateData(PERMISSION_NAME[PERMISSION_USER.LIST_ALL_USER], PERMISSION_USER.LIST_ALL_USER),
  generateData(PERMISSION_NAME[PERMISSION_USER.CREATE_UPDATE_REMOVE_USER], PERMISSION_USER.CREATE_UPDATE_REMOVE_USER),
  generateData(PERMISSION_NAME[PERMISSION_USER.READ_DETAIL_ACCOUNT], PERMISSION_USER.READ_DETAIL_ACCOUNT),
  generateData(PERMISSION_NAME[PERMISSION_USER.EXPORT_USER], PERMISSION_USER.EXPORT_USER),
];

const dataCompany = [
  // Company
  generateData(PERMISSION_NAME[PERMISSION_COMPANY.LIST_COMPANY], PERMISSION_COMPANY.LIST_COMPANY),
  generateData(
    PERMISSION_NAME[PERMISSION_COMPANY.CREATE_UPDATE_REMOVE_COMPANY],
    PERMISSION_COMPANY.CREATE_UPDATE_REMOVE_COMPANY,
  ),
  generateData(PERMISSION_NAME[PERMISSION_COMPANY.LIST_ALL_COMPANY], PERMISSION_COMPANY.LIST_ALL_COMPANY),
];

const dataBranch = [
  // Branch
  generateData(PERMISSION_NAME[PERMISSION_BRANCH.LIST_BRANCH], PERMISSION_BRANCH.LIST_BRANCH),
  generateData(PERMISSION_NAME[PERMISSION_BRANCH.LIST_ALL_BRANCH], PERMISSION_BRANCH.LIST_ALL_BRANCH),
  generateData(
    PERMISSION_NAME[PERMISSION_BRANCH.CREATE_UPDATE_REMOVE_BRANCH],
    PERMISSION_BRANCH.CREATE_UPDATE_REMOVE_BRANCH,
  ),
];

const dataService = [
  // Service
  generateData(PERMISSION_NAME[PERMISSION_SERVICE.LIST_SERVICE], PERMISSION_SERVICE.LIST_SERVICE),
  generateData(
    PERMISSION_NAME[PERMISSION_SERVICE.CREATE_UPDATE_REMOVE_SERVICE],
    PERMISSION_SERVICE.CREATE_UPDATE_REMOVE_SERVICE,
  ),
  generateData(PERMISSION_NAME[PERMISSION_SERVICE.LIST_ALL_SERVICE], PERMISSION_SERVICE.LIST_ALL_SERVICE),
];

const dataDepartment = [
  // Department
  generateData(PERMISSION_NAME[PERMISSION_DEPARTMENT.LIST_DEPARTMENT], PERMISSION_DEPARTMENT.LIST_DEPARTMENT),
  generateData(
    PERMISSION_NAME[PERMISSION_DEPARTMENT.CREATE_UPDATE_REMOVE_DEPARTMENT],
    PERMISSION_DEPARTMENT.CREATE_UPDATE_REMOVE_DEPARTMENT,
  ),
  generateData(PERMISSION_NAME[PERMISSION_DEPARTMENT.LIST_ALL_DEPARTMENT], PERMISSION_DEPARTMENT.LIST_ALL_DEPARTMENT),
];

const dataMarketing = [
  // Marketing
  generateData(PERMISSION_NAME[PERMISSION_MARKETING.LIST_ORDERS], PERMISSION_MARKETING.LIST_ORDERS),
  generateData(PERMISSION_NAME[PERMISSION_MARKETING.LIST_ALL_ORDERS], PERMISSION_MARKETING.LIST_ALL_ORDERS),
  generateData(PERMISSION_NAME[PERMISSION_MARKETING.CREATE_ORDERS], PERMISSION_MARKETING.CREATE_ORDERS),
  generateData(PERMISSION_NAME[PERMISSION_MARKETING.UPDATE_ORDERS], PERMISSION_MARKETING.UPDATE_ORDERS),
  generateData(PERMISSION_NAME[PERMISSION_MARKETING.READ_DETAIL_ORDERS], PERMISSION_MARKETING.READ_DETAIL_ORDERS),
  generateData(PERMISSION_NAME[PERMISSION_MARKETING.GET_STATS_ORDERS], PERMISSION_MARKETING.GET_STATS_ORDERS),
];

const dataSaleAdmin = [
  // Sale admin
  generateData(
    PERMISSION_NAME[PERMISSION_SALE_ADMIN.LIST_ORDERS_SALE_ADMIN],
    PERMISSION_SALE_ADMIN.LIST_ORDERS_SALE_ADMIN,
  ),
  generateData(
    PERMISSION_NAME[PERMISSION_SALE_ADMIN.LIST_ALL_ORDERS_SALE_ADMIN],
    PERMISSION_SALE_ADMIN.LIST_ALL_ORDERS_SALE_ADMIN,
  ),
  generateData(
    PERMISSION_NAME[PERMISSION_SALE_ADMIN.READ_DETAIL_ORDERS_SALE_ADMIN],
    PERMISSION_SALE_ADMIN.READ_DETAIL_ORDERS_SALE_ADMIN,
  ),
  generateData(
    PERMISSION_NAME[PERMISSION_SALE_ADMIN.UPDATE_ORDERS_SALE_ADMIN],
    PERMISSION_SALE_ADMIN.UPDATE_ORDERS_SALE_ADMIN,
  ),
  generateData(PERMISSION_NAME[PERMISSION_SALE_ADMIN.GET_STATS_ORDERS], PERMISSION_SALE_ADMIN.GET_STATS_ORDERS),
];

const dataTechnicalStaff = [
  // Technical staff
  generateData(PERMISSION_NAME[PERMISSION_TECHNICAL_STAFF.LIST_ORDER_NVKD], PERMISSION_TECHNICAL_STAFF.LIST_ORDER_NVKD),
  generateData(
    PERMISSION_NAME[PERMISSION_TECHNICAL_STAFF.LIST_ALL_ORDER_NVKD],
    PERMISSION_TECHNICAL_STAFF.LIST_ALL_ORDER_NVKD,
  ),
  generateData(
    PERMISSION_NAME[PERMISSION_TECHNICAL_STAFF.READ_DETAIL_ORDER_NVKD],
    PERMISSION_TECHNICAL_STAFF.READ_DETAIL_ORDER_NVKD,
  ),
  generateData(
    PERMISSION_NAME[PERMISSION_TECHNICAL_STAFF.UPDATE_ORDER_NVKD],
    PERMISSION_TECHNICAL_STAFF.UPDATE_ORDER_NVKD,
  ),
  generateData(
    PERMISSION_NAME[PERMISSION_TECHNICAL_STAFF.GET_STATS_ORDERS],
    PERMISSION_TECHNICAL_STAFF.GET_STATS_ORDERS,
  ),
];

const dataCustomerCare = [
  // Customer care
  generateData(PERMISSION_NAME[PERMISSION_CUSTOMER_CARE.LIST_ORDERS_CSKH], PERMISSION_CUSTOMER_CARE.LIST_ORDERS_CSKH),
  generateData(
    PERMISSION_NAME[PERMISSION_CUSTOMER_CARE.READ_DETAIL_ORDERS_CSKH],
    PERMISSION_CUSTOMER_CARE.READ_DETAIL_ORDERS_CSKH,
  ),
  generateData(
    PERMISSION_NAME[PERMISSION_CUSTOMER_CARE.LIST_ALL_ORDERS_CSKH],
    PERMISSION_CUSTOMER_CARE.LIST_ALL_ORDERS_CSKH,
  ),
  generateData(
    PERMISSION_NAME[PERMISSION_CUSTOMER_CARE.UPDATE_ORDERS_CSKH],
    PERMISSION_CUSTOMER_CARE.UPDATE_ORDERS_CSKH,
  ),
  generateData(PERMISSION_NAME[PERMISSION_CUSTOMER_CARE.GET_STATS_ORDERS], PERMISSION_CUSTOMER_CARE.GET_STATS_ORDERS),
];

const dataProduct = [
  // Product
  generateData(PERMISSION_NAME[PERMISSION_KEY.LIST_PRODUCT], PERMISSION_KEY.LIST_PRODUCT),
  generateData(
    PERMISSION_NAME[PERMISSION_KEY.CREATE_UPDATE_REMOVE_PRODUCT],
    PERMISSION_KEY.CREATE_UPDATE_REMOVE_PRODUCT,
  ),
  generateData(PERMISSION_NAME[PERMISSION_KEY.LIST_ALL_PRODUCT], PERMISSION_KEY.LIST_ALL_PRODUCT),
];

const dataRole = [
  // Role
  generateData(PERMISSION_NAME[PERMISSION_KEY.LIST_ROLE], PERMISSION_KEY.LIST_ROLE),
  generateData(PERMISSION_NAME[PERMISSION_KEY.CREATE_UPDATE_REMOVE_ROLE], PERMISSION_KEY.CREATE_UPDATE_REMOVE_ROLE),
  generateData(PERMISSION_NAME[PERMISSION_KEY.ADD_ROLE_FOR_USER], PERMISSION_KEY.ADD_ROLE_FOR_USER),
  generateData(PERMISSION_NAME[PERMISSION_KEY.VIEW_AUTHORIZED_USERS], PERMISSION_KEY.VIEW_AUTHORIZED_USERS),
];

const dataCustomer = [
  // Customer
  generateData(PERMISSION_NAME[PERMISSION_CUSTOMER.LIST_CUSTOMER], PERMISSION_CUSTOMER.LIST_CUSTOMER),
  generateData(
    PERMISSION_NAME[PERMISSION_CUSTOMER.CREATE_UPDATE_REMOVE_CUSTOMER],
    PERMISSION_CUSTOMER.CREATE_UPDATE_REMOVE_CUSTOMER,
  ),
  generateData(PERMISSION_NAME[PERMISSION_CUSTOMER.LIST_ALL_CUSTOMER], PERMISSION_CUSTOMER.LIST_ALL_CUSTOMER),
  generateData(PERMISSION_NAME[PERMISSION_CUSTOMER.EXPORT_EXCEL_CUSTOMER], PERMISSION_CUSTOMER.EXPORT_EXCEL_CUSTOMER),
  generateData(PERMISSION_NAME[PERMISSION_CUSTOMER.IMPORT_EXCEL_CUSTOMER], PERMISSION_CUSTOMER.IMPORT_EXCEL_CUSTOMER),
];

const dataRegion = [
  // Region
  generateData(PERMISSION_NAME[PERMISSION_REGION.LIST_REGION], PERMISSION_REGION.LIST_REGION),
  generateData(
    PERMISSION_NAME[PERMISSION_REGION.CREATE_UPDATE_REMOVE_REGION],
    PERMISSION_REGION.CREATE_UPDATE_REMOVE_REGION,
  ),
  generateData(PERMISSION_NAME[PERMISSION_REGION.LIST_ALL_REGION], PERMISSION_REGION.LIST_ALL_REGION),
];

const dataCampaign = [
  // Campaign
  generateData(PERMISSION_NAME[PERMISSION_CAMPAIGN.LIST_CAMPAIGN], PERMISSION_CAMPAIGN.LIST_CAMPAIGN),
  generateData(PERMISSION_NAME[PERMISSION_CAMPAIGN.LIST_ALL_CAMPAIGN], PERMISSION_CAMPAIGN.LIST_ALL_CAMPAIGN),
  generateData(
    PERMISSION_NAME[PERMISSION_CAMPAIGN.CREATE_UPDATE_REMOVE_CAMPAIGN],
    PERMISSION_CAMPAIGN.CREATE_UPDATE_REMOVE_CAMPAIGN,
  ),
];

const dataServicePack = [
  // Service Pack
  generateData(PERMISSION_NAME[PERMISSION_SERVICE_PACK.LIST], PERMISSION_SERVICE_PACK.LIST),
  generateData(PERMISSION_NAME[PERMISSION_SERVICE_PACK.LIST_ALL], PERMISSION_SERVICE_PACK.LIST_ALL),
  generateData(
    PERMISSION_NAME[PERMISSION_SERVICE_PACK.CREATE_UPDATE_REMOVE],
    PERMISSION_SERVICE_PACK.CREATE_UPDATE_REMOVE,
  ),
];

const dataStockCompany = [
  generateData(PERMISSION_NAME[PERMISSION_STOCK_COMPANY.MANAGER], PERMISSION_STOCK_COMPANY.MANAGER),
];

const dataStockBranch = [
  generateData(PERMISSION_NAME[PERMISSION_STOCK_BRANCH.MANAGER], PERMISSION_STOCK_BRANCH.MANAGER),
];

const dataPG = [generateData(PERMISSION_NAME[PERMISSION_PG.MANAGER], PERMISSION_PG.MANAGER)];

const dataAffiliate = [
  generateData(PERMISSION_NAME[PERMISSION_AFFILIATE.LIST_ORDERS], PERMISSION_AFFILIATE.LIST_ORDERS),
  generateData(PERMISSION_NAME[PERMISSION_AFFILIATE.CREATE_ORDERS], PERMISSION_AFFILIATE.CREATE_ORDERS),
  generateData(PERMISSION_NAME[PERMISSION_AFFILIATE.LIST_ALL_ORDERS], PERMISSION_AFFILIATE.LIST_ALL_ORDERS),
  generateData(PERMISSION_NAME[PERMISSION_AFFILIATE.UPDATE_ORDERS], PERMISSION_AFFILIATE.UPDATE_ORDERS),
  generateData(PERMISSION_NAME[PERMISSION_AFFILIATE.READ_DETAIL_ORDERS], PERMISSION_AFFILIATE.READ_DETAIL_ORDERS),
  generateData(PERMISSION_NAME[PERMISSION_AFFILIATE.GET_STATS_ORDERS], PERMISSION_AFFILIATE.GET_STATS_ORDERS),
];

const data = [
  ...dataPosition,
  ...dataUser,
  ...dataCompany,
  ...dataBranch,
  ...dataService,
  ...dataDepartment,
  ...dataMarketing,
  ...dataSaleAdmin,
  ...dataTechnicalStaff,
  ...dataCustomerCare,
  ...dataProduct,
  ...dataRole,
  ...dataCustomer,
  ...dataRegion,
  ...dataCampaign,
  ...dataServicePack,
  ...dataStockCompany,
  ...dataStockBranch,
  ...dataPG,
  ...dataAffiliate,
];

@Injectable()
export class PermissionSeed {
  constructor(
    @InjectRepository(Permission)
    protected readonly repository: Repository<Permission>,
  ) {}

  async seed() {
    const count = await this.repository.count();
    if (count) return;
    return this.repository.save(data);
  }
}
