export const USER_PATTERN = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  GET_TOKEN: 'USER_PATTERN.GET_TOKEN',
  GET_ME: 'USER_PATTERN.GET_ME',
  CREATE_USER: 'USER_PATTERN.CREATE_USER',
  LIST_USER: 'USER_PATTERN.LIST_USER',
  GET_ONE_USER: 'USER_PATTERN.GET_ONE_USER',
  GET_BULK_USER: 'USER_PATTERN.GET_BULK_USER',

  UPDATE_USER: 'USER_PATTERN.UPDATE_USER',
  ACCOUNT_LOCK: 'USER_PATTERN.ACCOUNT_LOCK',
  GET_USER_BY_UNIQUE_KEY: 'USER_PATTERN.GET_USER_BY_UNIQUE_KEY',
  GET_USER_BY_AUTHOR: 'USER_PATTERN.GET_USER_BY_AUTHOR',
  CHANGE_ROLE: 'USER_PATTERN.CHANGE_ROLE',
  LIST_ROLE_ID: 'USER_PATTERN.LIST_ROLE_ID',
  SET_NULL_ROLE_ID: 'USER_PATTERN.SET_NULL_ROLE_ID',
  FORGOT_PASSWORD: 'USER_PATTERN.FORGOT_PASSWORD',
  PRE_RESPONSE_USER: 'USER_PATTERN.PRE_RESPONSE_USER',
  DELETE_USER: 'USER_PATTERN.DELETE_USER',
  IS_USER_EXISTED: 'USER_PATTERN.IS_USER_EXISTED',
  BULK_DELETE_USER: 'USER_PATTERN.BULK_DELETE_USER',
  GET_SALE_ADMIN: 'USER_PATTERN.GET_SALE_ADMIN',
  UPLOAD_AVATAR: 'USER_PATTERN.UPLOAD_AVATAR',
  UPLOAD_BACKGROUND: 'USER_PATTERN.UPLOAD_BACKGROUND',

  USER_CATEGORY: 'USER_PATTERN.USER_CATEGORY',
  CHECK_PHONE_EXISTS: 'USER_PATTERN.CHECK_PHONE_EXISTS',
};

export const DEVICE_PATTERN = {
  LIST_DEVICE_USED: 'DEVICE_PATTERN.LIST_DEVICE_USED',
  GET_DEVICE_USED: 'DEVICE_PATTERN.GET_DEVICE_USED',
  LOGOUT_DEVICE_USED: 'DEVICE_PATTERN.LOGOUT_DEVICE_USED',

  GET_DEVICE_BY_DEVICE_ID: 'DEVICE_PATTERN.GET_DEVICE_BY_DEVICE_ID',
};

export const CATEGORY_PATTERN = {
  LIST_CATEGORY: 'CATEGORY_PATTERN.LIST_CATEGORY',
};

export const STORY_PATTERN = {
  LIST_STORY: 'STORY_PATTERN.LIST_STORY',
  
}

export const AUDIO_BOOK_PATTERN = {
  LIST_AUDIO_BOOK: 'AUDIO_BOOK_PATTERN.LIST_AUDIO_BOOK',
}

export const TOKEN_PATTERN = {
  VERIFY: 'TOKEN_PATTERN.VERIFY',
  CREATE_TOKEN: 'TOKEN_PATTERN.CREATE_TOKEN',
  CREATE_REFRESH_TOKEN: 'TOKEN_PATTERN.CREATE_REFRESH_TOKEN',
  UPDATE_REFRESH_TOKEN: 'TOKEN_PATTERN.UPDATE_REFRESH_TOKEN',
  TOKEN_DECODE: 'TOKEN_PATTERN.TOKEN_DECODE',
  AUTHENTICATION: 'TOKEN_PATTERN.AUTHENTICATION',
};

export const FILE_PATTERN = {
  UPLOAD_AVATAR: 'FILE_PATTERN.UPLOAD_AVATAR',
  EXPORT_LIST_USER: 'FILE_PATTERN.EXPORT_LIST_USER',
  UPLOAD_IMG_PRODUCT: 'FILE_PATTERN.UPLOAD_IMG_PRODUCT',
  UPLOAD_IMG_MARKETING: 'FILE_PATTERN.UPLOAD_IMG_MARKETING',
};

export const ROLE_PATTERN = {
  CREATE_ROLE: 'ROLE_PATTERN.CREATE_ROLE',
  GET_ROLE: 'ROLE_PATTERN.GET_ROLE',
  LIST_ROLE: 'ROLE_PATTERN.LIST_ROLE',
  UPDATE_ROLE: 'ROLE_PATTERN.UPDATE_ROLE',
  REMOVE_ROLE: 'ROLE_PATTERN.REMOVE_ROLE',
  CHANGE_ROLE_USER: 'ROLE_PATTERN.CHANGE_ROLE_USER',
  CHECK_ROLE: 'ROLE_PATTERN.CHECK_ROLE',
};

export const PERMISSION_PATTERN = {
  GET_PERMISSION: 'PERMISSION_PATTERN.GET_PERMISSION',
  LIST_PERMISSION: 'PERMISSION_PATTERN.LIST_PERMISSION',
};

export const BACKUP_PATTERN = {
  BACKUP_DATABASE: 'BACKUP_PATTERN.BACKUP_DATABASE',
  LIST_BACKUP: 'BACKUP_PATTERN.LIST_BACKUP',
};
