export enum PERMISSION_POSITION {
  // Position
  LIST_POSITION = 'POSITION.LIST_POSITION',
  LIST_ALL_POSITION = 'POSITION.LIST_ALL_POSITION',
  CREATE_UPDATE_REMOVE_POSITION = 'POSITION.CREATE_UPDATE_REMOVE_POSITION',
}

export enum PERMISSION_CAMPAIGN {
  // Campaign
  LIST_CAMPAIGN = 'CAMPAIGN.LIST_CAMPAIGN',
  LIST_ALL_CAMPAIGN = 'CAMPAIGN.LIST_ALL_CAMPAIGN',
  CREATE_UPDATE_REMOVE_CAMPAIGN = 'CAMPAIGN.CREATE_UPDATE_REMOVE_CAMPAIGN',
}

export enum PERMISSION_CUSTOMER_CARE {
  // CSKH
  LIST_ORDERS_CSKH = 'CSKH.LIST_ORDERS_CSKH',
  LIST_ALL_ORDERS_CSKH = 'CSKH.LIST_ALL_ORDERS_CSKH',
  READ_DETAIL_ORDERS_CSKH = 'CSKH.READ_DETAIL_ORDERS_CSKH',
  UPDATE_ORDERS_CSKH = 'CSKH.UPDATE_ORDERS_CSKH',
  GET_STATS_ORDERS = 'CSKH.GET_STATS_ORDERS',
}

export enum PERMISSION_SALE_ADMIN {
  // Sale Admin
  LIST_ORDERS_SALE_ADMIN = 'SALEADMIN.LIST_ORDERS_SALE_ADMIN',
  LIST_ALL_ORDERS_SALE_ADMIN = 'SALEADMIN.LIST_ALL_ORDERS_SALE_ADMIN',
  READ_DETAIL_ORDERS_SALE_ADMIN = 'SALEADMIN.READ_DETAIL_ORDERS_SALE_ADMIN',
  UPDATE_ORDERS_SALE_ADMIN = 'SALEADMIN.UPDATE_ORDERS_SALE_ADMIN',
  GET_STATS_ORDERS = 'SALEADMIN.GET_STATS_ORDERS',
}

export enum PERMISSION_AFFILIATE {
  // Affiliate
  CREATE_ORDERS = 'AFFILIATE.CREATE_ORDERS',
  LIST_ORDERS = 'AFFILIATE.LIST_ORDERS',
  LIST_ALL_ORDERS = 'AFFILIATE.LIST_ALL_ORDERS',
  READ_DETAIL_ORDERS = 'AFFILIATE.READ_DETAIL_ORDERS',
  UPDATE_ORDERS = 'AFFILIATE.UPDATE_ORDERS',
  GET_STATS_ORDERS = 'AFFILIATE.GET_STATS_ORDERS',
}

export enum PERMISSION_COMPANY {
  // Company
  LIST_COMPANY = 'COMPANY.LIST_COMPANY',
  LIST_ALL_COMPANY = 'COMPANY.LIST_ALL_COMPANY',
  CREATE_UPDATE_REMOVE_COMPANY = 'COMPANY.CREATE_UPDATE_REMOVE_COMPANY',
}

export enum PERMISSION_BRANCH {
  // Branch
  LIST_BRANCH = 'BRANCH.LIST_BRANCH',
  LIST_ALL_BRANCH = 'BRANCH.LIST_ALL_BRANCH',
  CREATE_UPDATE_REMOVE_BRANCH = 'BRANCH.CREATE_UPDATE_REMOVE_BRANCH',
}

export enum PERMISSION_REGION {
  // Region
  LIST_REGION = 'REGION.LIST_REGION',
  LIST_ALL_REGION = 'REGION.LIST_ALL_REGION',
  CREATE_UPDATE_REMOVE_REGION = 'REGION.CREATE_UPDATE_REMOVE_REGION',
}

export enum PERMISSION_SERVICE {
  // Service
  LIST_SERVICE = 'SERVICE.LIST_SERVICE',
  LIST_ALL_SERVICE = 'SERVICE.LIST_ALL_SERVICE',
  CREATE_UPDATE_REMOVE_SERVICE = 'SERVICE.CREATE_UPDATE_REMOVE_SERVICE',
}

export enum PERMISSION_DEPARTMENT {
  // Department
  LIST_DEPARTMENT = 'DEPARTMENT.LIST_DEPARTMENT',
  LIST_ALL_DEPARTMENT = 'DEPARTMENT.LIST_ALL_DEPARTMENT',
  CREATE_UPDATE_REMOVE_DEPARTMENT = 'DEPARTMENT.CREATE_UPDATE_REMOVE_DEPARTMENT',
}

export enum PERMISSION_SERVICE_PACK {
  // Service pack
  LIST = 'SERVICE_PACK.LIST',
  LIST_ALL = 'SERVICE_PACK.LIST_ALL',
  CREATE_UPDATE_REMOVE = 'SERVICE_PACK.CREATE_UPDATE_REMOVE',
}

export enum PERMISSION_STOCK_COMPANY {
  // Stock company
  MANAGER = 'STOCK_COMPANY.MANAGER',
}

export enum PERMISSION_STOCK_BRANCH {
  // Stock branch
  MANAGER = 'STOCK_BRANCH.MANAGER',
}

export enum PERMISSION_PG {
  // PG
  MANAGER = 'PG.MANAGER',
}

export enum PERMISSION_MARKETING {
  // Orders Marketing
  LIST_ORDERS = 'MARKETING.LIST_ORDERS',
  LIST_ALL_ORDERS = 'MARKETING.LIST_ALL_ORDERS',
  READ_DETAIL_ORDERS = 'MARKETING.READ_DETAIL_ORDERS',
  CREATE_ORDERS = 'MARKETING.CREATE_ORDERS',
  UPDATE_ORDERS = 'MARKETING.UPDATE_ORDERS',
  GET_STATS_ORDERS = 'MARKETING.GET_STATS_ORDERS',
}

export enum PERMISSION_TECHNICAL_STAFF {
  // NVKD
  LIST_ORDER_NVKD = 'NVKD.LIST_ORDER_NVKD',
  LIST_ALL_ORDER_NVKD = 'NVKD.LIST_ALL_ORDER_NVKD',
  UPDATE_ORDER_NVKD = 'NVKD.UPDATE_ORDER_NVKD',
  READ_DETAIL_ORDER_NVKD = 'NVKD.READ_DETAIL_ORDER_NVKD',
  GET_STATS_ORDERS = 'NVKD.GET_STATS_ORDERS',
}

export enum PERMISSION_CUSTOMER {
  // Customer
  LIST_CUSTOMER = 'CUSTOMER.LIST_CUSTOMER',
  LIST_ALL_CUSTOMER = 'CUSTOMER.LIST_ALL_CUSTOMER',
  CREATE_UPDATE_REMOVE_CUSTOMER = 'CUSTOMER.CREATE_UPDATE_REMOVE_CUSTOMER',
  EXPORT_EXCEL_CUSTOMER = 'CUSTOMER.EXPORT_EXCEL_CUSTOMER',
  IMPORT_EXCEL_CUSTOMER = 'CUSTOMER.IMPORT_EXCEL_CUSTOMER',
}

export enum PERMISSION_USER {
  // User
  LIST_USER = 'USER.LIST_USER',
  LIST_ALL_USER = 'USER.LIST_ALL_USER',
  CREATE_UPDATE_REMOVE_USER = 'USER.CREATE_UPDATE_REMOVE_USER',
  READ_DETAIL_ACCOUNT = 'USER.READ_DETAIL_ACCOUNT',
  EXPORT_USER = 'USER.EXPORT_USER',
}

export enum PERMISSION_KEY {
  // TODO: Tách ra enum khác
  // Product
  LIST_PRODUCT = 'PRODUCT.LIST_PRODUCT',
  LIST_ALL_PRODUCT = 'PRODUCT.LIST_ALL_PRODUCT',
  CREATE_UPDATE_REMOVE_PRODUCT = 'PRODUCT.CREATE_UPDATE_REMOVE_PRODUCT',

  // Role
  LIST_ROLE = 'ROLE.LIST_ROLE',
  CREATE_UPDATE_REMOVE_ROLE = 'ROLE.CREATE_UPDATE_REMOVE_ROLE',
  ADD_ROLE_FOR_USER = 'ROLE.ADD_ROLE_FOR_USER',
  VIEW_AUTHORIZED_USERS = 'ROLE.VIEW_AUTHORIZED_USERS',
  ADD_UPDATE_REMOVE_ROLE_FOR_USER = 'ROLE.ADD_UPDATE_REMOVE_ROLE_FOR_USER',
}

export const PERMISSION_NAME: Record<string, string> = {
  // Position
  [PERMISSION_POSITION.LIST_POSITION]: 'Quyền xem danh sách chức vụ',
  [PERMISSION_POSITION.LIST_ALL_POSITION]: 'Quyền xem tất cả danh sách chức vụ',
  [PERMISSION_POSITION.CREATE_UPDATE_REMOVE_POSITION]: 'Quyền thêm/sửa/xóa chức vụ',

  // User
  [PERMISSION_USER.LIST_USER]: 'Quyền xem danh sách người dùng',
  [PERMISSION_USER.LIST_ALL_USER]: 'Quyền xem tất cả danh sách người dùng',
  [PERMISSION_USER.CREATE_UPDATE_REMOVE_USER]: 'Quyền thêm/sửa/xóa người dùng',
  [PERMISSION_USER.READ_DETAIL_ACCOUNT]: 'Quyền xem chi tiết tài khoản',
  [PERMISSION_USER.EXPORT_USER]: 'Quyền xuất danh sách người dùng',

  // Company
  [PERMISSION_COMPANY.LIST_COMPANY]: 'Quyền xem công ty',
  [PERMISSION_COMPANY.LIST_ALL_COMPANY]: 'Quyền xem tất cả công ty',
  [PERMISSION_COMPANY.CREATE_UPDATE_REMOVE_COMPANY]: 'Quyền thêm/sửa/xóa công ty',

  // Region
  [PERMISSION_REGION.LIST_REGION]: 'Quyền xem vùng',
  [PERMISSION_REGION.LIST_ALL_REGION]: 'Quyền xem tất cả vùng',
  [PERMISSION_REGION.CREATE_UPDATE_REMOVE_REGION]: 'Quyền thêm/sửa/xóa vùng',

  // Branch
  [PERMISSION_BRANCH.LIST_BRANCH]: 'Quyền xem showroom',
  [PERMISSION_BRANCH.LIST_ALL_BRANCH]: 'Quyền xem tất cả showroom',
  [PERMISSION_BRANCH.CREATE_UPDATE_REMOVE_BRANCH]: 'Quyền thêm/sửa/xóa showroom',

  // Campaign
  [PERMISSION_CAMPAIGN.LIST_CAMPAIGN]: 'Quyền xem chiến dịch',
  [PERMISSION_CAMPAIGN.LIST_ALL_CAMPAIGN]: 'Quyền xem tất cả chiến dịch',
  [PERMISSION_CAMPAIGN.CREATE_UPDATE_REMOVE_CAMPAIGN]: 'Quyền thêm/sửa/xóa chiến dịch',

  // Service
  [PERMISSION_SERVICE.LIST_SERVICE]: 'Quyền xem dịch vụ',
  [PERMISSION_SERVICE.LIST_ALL_SERVICE]: 'Quyền xem tất cả dịch vụ',
  [PERMISSION_SERVICE.CREATE_UPDATE_REMOVE_SERVICE]: 'Quyền tạo/sửa/xóa dịch vụ',

  // Department
  [PERMISSION_DEPARTMENT.LIST_DEPARTMENT]: 'Quyền xem phòng ban',
  [PERMISSION_DEPARTMENT.LIST_ALL_DEPARTMENT]: 'Quyền xem tất cả phòng ban',
  [PERMISSION_DEPARTMENT.CREATE_UPDATE_REMOVE_DEPARTMENT]: 'Quyền tạo/sửa/xóa phòng ban',

  // Marketing
  [PERMISSION_MARKETING.LIST_ORDERS]: 'Quyền xem danh sách đơn hàng Marketing của cá nhân',
  [PERMISSION_MARKETING.LIST_ALL_ORDERS]: 'Quyền xem danh sách tất cả đơn hàng Marketing',
  [PERMISSION_MARKETING.CREATE_ORDERS]: 'Quyền tạo đơn hàng Marketing',
  [PERMISSION_MARKETING.UPDATE_ORDERS]: 'Quyền sửa đơn hàng Marketing',
  [PERMISSION_MARKETING.READ_DETAIL_ORDERS]: 'Quyền xem chi tiết đơn hàng Marketing',
  [PERMISSION_MARKETING.GET_STATS_ORDERS]: 'Quyền xem chi thống kê đơn hàng Marketing',

  // Customer care
  [PERMISSION_CUSTOMER_CARE.LIST_ORDERS_CSKH]: 'Quyền xem danh sách đơn hàng CSKH của cá nhân',
  [PERMISSION_CUSTOMER_CARE.LIST_ALL_ORDERS_CSKH]: 'Quyền xem tất cả danh sách đơn hàng CSKH',
  [PERMISSION_CUSTOMER_CARE.READ_DETAIL_ORDERS_CSKH]: 'Quyền xem chi tiết đơn hàng CSKH',
  [PERMISSION_CUSTOMER_CARE.UPDATE_ORDERS_CSKH]: 'Quyền sửa đơn hàng CSKH',
  [PERMISSION_CUSTOMER_CARE.GET_STATS_ORDERS]: 'Quyền thống kê đơn hàng của chăm sóc khách hàng',

  // Sale admin
  [PERMISSION_SALE_ADMIN.LIST_ORDERS_SALE_ADMIN]: 'Quyền xem danh sách đơn hàng Sale admin của cá nhân',
  [PERMISSION_SALE_ADMIN.LIST_ALL_ORDERS_SALE_ADMIN]: 'Quyền xem tất cả danh sách đơn hàng Sale admin',
  [PERMISSION_SALE_ADMIN.READ_DETAIL_ORDERS_SALE_ADMIN]: 'Quyền xem chi tiết đơn hàng Sale admin',
  [PERMISSION_SALE_ADMIN.UPDATE_ORDERS_SALE_ADMIN]: 'Quyền sửa đơn hàng Sale admin',
  [PERMISSION_SALE_ADMIN.GET_STATS_ORDERS]: 'Quyền xem thống kê đơn hàng Sale admin',

  // NVKD
  [PERMISSION_TECHNICAL_STAFF.LIST_ORDER_NVKD]: 'Quyền xem đơn hàng NVKD của cá nhân',
  [PERMISSION_TECHNICAL_STAFF.LIST_ALL_ORDER_NVKD]: 'Quyền xem tất cả đơn hàng NVKD',
  [PERMISSION_TECHNICAL_STAFF.UPDATE_ORDER_NVKD]: 'Quyền cập nhật đơn hàng NVKD',
  [PERMISSION_TECHNICAL_STAFF.READ_DETAIL_ORDER_NVKD]: 'Quyền xem chi tiết đơn hàng NVKD',
  [PERMISSION_TECHNICAL_STAFF.GET_STATS_ORDERS]: 'Quyền xem thống kê đơn hàng NVKD',

  // Product
  [PERMISSION_KEY.LIST_PRODUCT]: 'Quyền xem danh sách sản phẩm',
  [PERMISSION_KEY.LIST_ALL_PRODUCT]: 'Quyền xem tất cả danh sách sản phẩm',
  [PERMISSION_KEY.CREATE_UPDATE_REMOVE_PRODUCT]: 'Quyền tạo/sửa/xóa sản phẩm',

  // Role
  [PERMISSION_KEY.LIST_ROLE]: 'Quyền xem danh sách nhóm quyền',
  [PERMISSION_KEY.CREATE_UPDATE_REMOVE_ROLE]: 'Quyền tạo/sửa/xóa nhóm quyền',
  [PERMISSION_KEY.ADD_ROLE_FOR_USER]: 'Quyền gán quyền nhóm quyền',
  [PERMISSION_KEY.VIEW_AUTHORIZED_USERS]: 'Quyền xem danh sách nhân sự được gán quyền',
  [PERMISSION_KEY.ADD_UPDATE_REMOVE_ROLE_FOR_USER]: 'Quyền gán/sửa/xóa nhóm quyền cho nhân sự',

  // Customer
  [PERMISSION_CUSTOMER.LIST_CUSTOMER]: 'Quyền xem tìm kiếm khách hàng',
  [PERMISSION_CUSTOMER.LIST_ALL_CUSTOMER]: 'Quyền xem tất cả danh sách khách hàng',
  [PERMISSION_CUSTOMER.CREATE_UPDATE_REMOVE_CUSTOMER]: 'Quyền thêm/sửa/xóa khách hàng',
  [PERMISSION_CUSTOMER.EXPORT_EXCEL_CUSTOMER]: 'Quyền xuất excel khách hàng',
  [PERMISSION_CUSTOMER.IMPORT_EXCEL_CUSTOMER]: 'Quyền nhập excel khách hàng',

  // Service pack
  [PERMISSION_SERVICE_PACK.LIST]: 'Quyền xem danh sách gói dịch vụ',
  [PERMISSION_SERVICE_PACK.LIST_ALL]: 'Quyền xem tất cả gói dịch vụ',
  [PERMISSION_SERVICE_PACK.CREATE_UPDATE_REMOVE]: 'Quyền thêm/sửa/xóa gói dịch vụ',

  // Stock company
  [PERMISSION_STOCK_COMPANY.MANAGER]: 'Quyền quản lý kho công ty',

  // Stock branch
  [PERMISSION_STOCK_BRANCH.MANAGER]: 'Quyền quản lý kho chi nhánh',

  // Stock PG
  [PERMISSION_PG.MANAGER]: 'Quyền PG',

  // Affiliate
  [PERMISSION_AFFILIATE.LIST_ORDERS]: 'Quyền xem đơn hàng Affiliate của cá nhân',
  [PERMISSION_AFFILIATE.CREATE_ORDERS]: 'Quyền tạo đơn hàng Affiliate',
  [PERMISSION_AFFILIATE.LIST_ALL_ORDERS]: 'Quyền xem tất cả đơn hàng Affiliate',
  [PERMISSION_AFFILIATE.READ_DETAIL_ORDERS]: 'Quyền xem chi tiết đơn hàng Affiliate',
  [PERMISSION_AFFILIATE.UPDATE_ORDERS]: 'Quyền cập nhật đơn hàng Affiliate',
  [PERMISSION_AFFILIATE.GET_STATS_ORDERS]: 'Quyền xem thống kê đơn hàng Affiliate',
};
