pipeline {
    agent {
        node {
            label 'anmoga-remote'
        }
    }
    environment {
        NEW_VERSION = '1.0.0'
    }
    stages {
        stage('Build') {
            steps {
                echo 'Building..'
                echo "Build version ${NEW_VERSION}"
            }
        }
        stage('Test') {
            steps {
                echo 'Testing...'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying...'
                
            }
        }
    }
}
