apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.23-alpine
          resources:
            limits:
              memory: '128Mi'
              cpu: '250m'
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anmoga-be-gateway
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: anmoga-be-gateway
  template:
    metadata:
      labels:
        app: anmoga-be-gateway
    spec:
      containers:
        - name: anmoga-be-gateway
          image: {{ .Values.gateway.image }}:{{ .Values.gateway.version }}
          resources:
            limits:
              memory: '128Mi'
              cpu: '250m'
          ports:
            - containerPort: 3001
---
