apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
    - port: 8000
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Chart.Name }}
  ports:
    - port: 3001
      targetPort: 3001
